import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import variablesForward from "../src/index.js";

const tempDirs: string[] = [];
type VariablesForwardPlugin = ReturnType<typeof variablesForward>;
type StringSplitForPlugin = (
  this: string,
  separator: string,
  limit?: number,
) => string[];
const splitString = (
  value: string,
  separator: string,
  limit?: number,
): string[] => {
  return value.split(separator, limit);
};

const invokeBuildStart = async (
  plugin: VariablesForwardPlugin,
): Promise<void> => {
  const buildStart = plugin.buildStart;
  if (!buildStart) {
    throw new Error("buildStart hook is missing");
  }

  if (typeof buildStart === "function") {
    await buildStart.call(
      {} as ThisParameterType<typeof buildStart>,
      {} as Parameters<typeof buildStart>[0],
    );
    return;
  }

  await buildStart.handler.call(
    {} as ThisParameterType<typeof buildStart.handler>,
    {} as Parameters<typeof buildStart.handler>[0],
  );
};

const createTempDir = (): string => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "variables-forward-"));
  tempDirs.push(dir);
  return dir;
};

const sleep = async (ms: number): Promise<void> => {
  await new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
};

const waitForFileContent = async (filePath: string): Promise<string> => {
  for (let attempt = 0; attempt < 20; attempt += 1) {
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, "utf-8");
      if (content.length > 0) {
        return content;
      }
    }
    await sleep(10);
  }

  throw new Error(`Timed out waiting for ${filePath}`);
};

const countTrailingNewlines = (value: string): number => {
  const match = /\n+$/.exec(value);
  return match ? match[0].length : 0;
};

afterEach(() => {
  vi.restoreAllMocks();
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

describe("variablesForward", () => {
  it("generates @forward with from SCSS variables", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "_variables.scss");
    const to = path.join(dir, "_variables-forward.scss");

    fs.writeFileSync(
      from,
      ["$primary-color: #ff0000;", "$secondary-color: #00ff00;"].join("\n"),
    );

    const info = vi.spyOn(console, "info").mockImplementation(() => undefined);
    const plugin = variablesForward({
      from,
      to,
      module: "theme",
    });

    await invokeBuildStart(plugin);

    const content = await waitForFileContent(to);

    expect(content).toBe(`// DO NOT EDIT THIS FILE MANUALLY.
// This file is auto-generated by vite-plugin-create-variables-forward from ${from}.
@use 'variables' as var;
@forward 'theme' with (
  $primary-color: var.$primary-color,
  $secondary-color: var.$secondary-color
);
`);
    expect(countTrailingNewlines(content)).toBe(1);
    expect(info).toHaveBeenCalledWith(`Created ${to}`);
  });

  it("appends additional @forward directives", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "_variables.scss");
    const to = path.join(dir, "_variables-forward.scss");

    fs.writeFileSync(from, "$primary-color: #ff0000;\n");

    const plugin = variablesForward({
      from,
      to,
      module: "theme",
      modules: ["other-theme", "legacy-theme"],
    });

    await invokeBuildStart(plugin);

    const content = await waitForFileContent(to);

    expect(content).toBe(`// DO NOT EDIT THIS FILE MANUALLY.
// This file is auto-generated by vite-plugin-create-variables-forward from ${from}.
@use 'variables' as var;
@forward 'theme' with (
  $primary-color: var.$primary-color
);
@forward 'other-theme';
@forward 'legacy-theme';
`);
    expect(countTrailingNewlines(content)).toBe(1);
  });

  it("creates a relative @use path from the output file", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "styles", "_variables.scss");
    const to = path.join(dir, "generated", "_variables-forward.scss");

    fs.mkdirSync(path.dirname(from), { recursive: true });
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.writeFileSync(from, "$primary-color: #ff0000;\n");

    const plugin = variablesForward({
      from,
      to,
      module: "theme",
    });

    await invokeBuildStart(plugin);

    expect(await waitForFileContent(to)).toContain(
      "@use '../styles/variables' as var;",
    );
  });

  it("creates a relative @use path across different directory levels", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "src", "styles", "tokens", "_variables.scss");
    const to = path.join(
      dir,
      "packages",
      "ui",
      "generated",
      "_variables-forward.scss",
    );

    fs.mkdirSync(path.dirname(from), { recursive: true });
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.writeFileSync(from, "$primary-color: #ff0000;\n");

    const plugin = variablesForward({
      from,
      to,
      module: "theme",
    });

    await invokeBuildStart(plugin);

    expect(await waitForFileContent(to)).toContain(
      "@use '../../../src/styles/tokens/variables' as var;",
    );
  });

  it("removes only one leading underscore from the @use path", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "styles", "__variables.scss");
    const to = path.join(dir, "generated", "_variables-forward.scss");

    fs.mkdirSync(path.dirname(from), { recursive: true });
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.writeFileSync(from, "$primary-color: #ff0000;\n");

    const plugin = variablesForward({
      from,
      to,
      module: "theme",
    });

    await invokeBuildStart(plugin);

    expect(await waitForFileContent(to)).toContain(
      "@use '../styles/_variables' as var;",
    );
  });

  it("does not generate output when no variables exist", async () => {
    const dir = createTempDir();
    const from = path.join(dir, "_variables.scss");
    const to = path.join(dir, "_variables-forward.scss");

    fs.writeFileSync(from, ".button { color: red; }\n");

    const info = vi.spyOn(console, "info").mockImplementation(() => undefined);
    const plugin = variablesForward({
      from,
      to,
      module: "theme",
    });

    await invokeBuildStart(plugin);

    expect(fs.existsSync(to)).toBe(false);
    expect(info).not.toHaveBeenCalled();
  });

  it("skips entries when the parsed key is empty", async () => {
    const readFileSync = vi
      .spyOn(fs, "readFileSync")
      .mockReturnValue("$broken:");
    vi.spyOn(
      String.prototype as { split: StringSplitForPlugin },
      "split",
    ).mockImplementation(function (
      this: string,
      separator: string,
      limit?: number,
    ) {
      if (this === "$broken:" && separator === "\n") {
        return ["$broken:"];
      }
      if (this === "$broken:" && separator === ":") {
        return [""];
      }
      return splitString(this, separator, limit);
    });
    const writeFile = vi.spyOn(fs, "writeFile");
    const info = vi.spyOn(console, "info").mockImplementation(() => undefined);
    const plugin = variablesForward({
      from: "ignored.scss",
      to: "ignored-output.scss",
      module: "theme",
    });

    await invokeBuildStart(plugin);

    expect(readFileSync).toHaveBeenCalled();
    expect(writeFile).not.toHaveBeenCalled();
    expect(info).not.toHaveBeenCalled();
  });

  it("throws when writeFile fails", async () => {
    const writeFileError = new Error("write failed");
    vi.spyOn(fs, "readFileSync").mockReturnValue("$primary-color: #ff0000;");
    vi.spyOn(fs, "writeFile").mockImplementation((_, __, callback) => {
      if (typeof callback === "function") {
        callback(writeFileError);
      }
    });
    const plugin = variablesForward({
      from: "ignored.scss",
      to: "ignored-output.scss",
      module: "theme",
    });

    await expect(invokeBuildStart(plugin)).rejects.toThrow(writeFileError);
  });
});
